# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rztpois_single <- function(lambda) {
    .Call(`_dpfa_rztpois_single`, lambda)
}

rztpois_cpp <- function(n, lambda) {
    .Call(`_dpfa_rztpois_cpp`, n, lambda)
}

calcC_kn <- function(ZZip_3D, bias_0, W_3D, Phi) {
    .Call(`_dpfa_calcC_kn`, ZZip_3D, bias_0, W_3D, Phi)
}

calcTheta <- function(rk, ZZip, x_kn, p0) {
    .Call(`_dpfa_calcTheta`, rk, ZZip, x_kn, p0)
}

calcW <- function(sk, ZZip, C_k1n, p0) {
    .Call(`_dpfa_calcW`, sk, ZZip, C_k1n, p0)
}

mult_cpp <- function(X_mtn, Psi, Theta, ZZip) {
    .Call(`_dpfa_mult_cpp`, X_mtn, Psi, Theta, ZZip)
}

crt_cpp <- function(X_kn, rk) {
    .Call(`_dpfa_crt_cpp`, X_kn, rk)
}

